# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b785b40cbaba985e459c7432681751b51868634112232b1fa776abaead7963c72e3f91e26ca74e1b125177dbec9a082509aeea704f1db86bee556679ec4a6ba2

test:
  secret_key_base: 661b692db285ca857a414298e14152dde9afa11a18645436afc30bd8fd03d30411207a6ec83e46887294bb7a7c5687589c8b767bc8769bcd22ec5f1918ef0088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
